#!/bin/bash

set -e

ver="$(dpkg-parsechangelog  --show-field VERSION).c${BUILD_NUMBER:?}.g$(git rev-parse --short HEAD)"
dist="$(dpkg-parsechangelog  --show-field DISTRIBUTION)"

export DEBEMAIL=nobody@linutronix.de
export DEBFULLNAME=nobody

debchange --newversion "$ver" --distribution "$dist" --urgency low "CI version"
