#!/usr/bin/env python
#
# ELBE - Debian Based Embedded Rootfilesystem Builder
# Copyright (C) 2013  Linutronix GmbH
#
# This file is part of ELBE.
#
# ELBE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ELBE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ELBE.  If not, see <http://www.gnu.org/licenses/>.

import sys

from pkgutil import iter_modules
import elbepack.commands
from elbepack.version import elbe_version

def get_cmdlist():
    return [ x for _, x, _ in iter_modules(elbepack.commands.__path__) ]

def usage():
    print 'elbe v' + elbe_version
    print 'need a subcommand: e.g. \'elbe init\'. \n\
    Available subcommands are: \n'
    for i in get_cmdlist():
        print '        * '+i


if (len(sys.argv) < 2):
    usage()
    sys.exit(20)

if sys.argv[1] == "--version":
    print 'elbe v' + elbe_version
    sys.exit(0)

cmd_list = get_cmdlist()

if not sys.argv[1] in cmd_list:
    print "Unknown subcommand !\n"
    usage()
    sys.exit(20)

modname = "elbepack.commands."+sys.argv[1]

mod = __import__(modname)
cmdmod = sys.modules[modname]

cmdmod.run_command( sys.argv[2:] )
