#!/usr/bin/env python3

# ELBE - Debian Based Embedded Rootfilesystem Builder
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024 Linutronix GmbH

import dataclasses
import pathlib
import subprocess
import sys
import tempfile
import textwrap
import unittest

from elbepack.treeutils import etree

import elbevalidate
import elbevalidate.pytest


@dataclasses.dataclass
class ImageConfiguration:
    name: str
    disk_images: list
    tar_images: list


def get_image_configuration(build_dir):
    xml = etree(build_dir / 'source.xml')
    project_name = xml.text('project/name')
    disk_image = xml.text('target/images/msdoshd/name', default=None)
    tar_image = xml.text('target/package/base-image/name', default=None)
    return ImageConfiguration(name=project_name, disk_images=[disk_image] if disk_image else [],
                              tar_images=[tar_image] if tar_image else [])


def test_build_directory_contents(build_dir):
    test_config = get_image_configuration(build_dir)
    created_files = list([p.name for p in build_dir.iterdir()])
    for f in [
            'elbe-report.txt',
            'licence-chroot.txt',
            'licence-chroot.xml',
            'licence-target.txt',
            'licence-target.xml',
            'log.txt',
            'source.xml',
            'validation.txt',
            ] + test_config.disk_images + test_config.tar_images:

        assert f in created_files


def test_validation_txt(build_dir):
    assert build_dir.joinpath('validation.txt').read_text().strip() in [
        textwrap.dedent("""
            ELBE Package validation
            =======================

            Package List validation
            -----------------------

            No Errors found

            Archive validation
            ------------------
        """).strip(),

        textwrap.dedent("""
            ELBE Package validation
            =======================

            Package List validation
            -----------------------

            No Errors found

            Archive validation
            ------------------

            Binary CD
            Source CD
        """).strip()
    ]


def test_elbe_report_txt(build_dir):
    test_config = get_image_configuration(build_dir)
    elbe_report = build_dir.joinpath('elbe-report.txt').read_text()

    assert elbe_report.startswith(f'ELBE Report for Project {test_config.name}')

    assert textwrap.dedent("""
        Apt Sources dump
        ----------------

        deb [arch=amd64] http://deb.debian.org/debian trixie main


        Apt Preferences dump
        --------------------
    """) in elbe_report or textwrap.dedent("""
        Apt Sources dump
        ----------------

        deb-src [] http://deb.debian.org/debian trixie main
        deb [arch=amd64] http://deb.debian.org/debian trixie main


        Apt Preferences dump
        --------------------
    """) in elbe_report

    assert textwrap.dedent("""
        Apt Preferences dump
        --------------------





        Installed Packages List
        -----------------------
    """) in elbe_report

    if test_config.name == 'simple-validation-image':
        assert textwrap.dedent("""
        Installed Packages List
        -----------------------

        Local
        ~~~~~

        |libgpio3|3.0.1| trixie main

        Debian
        ~~~~~~

        |adduser|
        """.rstrip()) in elbe_report
    else:
        assert textwrap.dedent("""
        Installed Packages List
        -----------------------




        |libgpio3|3.0.1|  now

        Debian
        ~~~~~~

        |adduser|
        """.rstrip()) in elbe_report

    assert textwrap.dedent("""
        File List
        ---------

        |+//initrd.img+|postinst generated
    """) in elbe_report

    assert '\n|+/usr/bin/mount+|mount\n' in elbe_report


def test_elbe_log_txt(build_dir):
    test_config = get_image_configuration(build_dir)
    log = build_dir.joinpath('log.txt').read_text()

    assert log.startswith('[INFO]Build started\n')

    if test_config.name == 'simple-validation-extended-image':
        assert '[INFO]|util-linux|' in log
    else:
        assert 'I: Extracting util-linux...' in log
        assert '[CMD] cat /etc/hosts | cat -n > /etc/hosts4' in log

    assert log.endswith('[INFO]Build finished successfully\n')


def _test_generated_elbe_files(build_dir, root, image_name):
    elbe_version = root.joinpath('etc', 'elbe_version').read_text()
    assert elbe_version.startswith(f'{image_name} 1.0\nthis RFS was generated by elbe')

    assert root.joinpath('etc', 'updated_version').read_text() == '1.0'

    img_elbe_xml = root.joinpath('etc', 'elbe_base.xml').read_text()
    build_dir_elbe_xml = build_dir.joinpath('source.xml').read_text()

    assert img_elbe_xml == build_dir_elbe_xml


def _test_finetuning(root, image_name):
    # <rm>var/cache/apt/archives/*.deb</rm>
    for f in root.joinpath('var', 'cache', 'apt', 'archives').iterdir():
        assert f.suffix != '.deb'

    # <mkdir>/var/cache/test-dir</mkdir>
    assert root.joinpath('var', 'cache', 'test-dir').is_dir()

    # <mknod opts="c 0 5">/dev/null2</mknod>
    assert root.joinpath('dev', 'null2').is_char_device()

    # <cp path="/etc/hosts">/etc/hosts2</cp>
    assert root.joinpath('etc', 'hosts2').is_file()
    hosts_text = root.joinpath('etc', 'hosts').read_text()
    hosts2_text = root.joinpath('etc', 'hosts2').read_text()
    if image_name == 'simple-validation-extended-image':
        assert hosts2_text in hosts_text
    else:
        assert hosts2_text == hosts_text

    # <mv path="/etc/issue">/etc/issue2</mv>
    assert root.joinpath('etc', 'issue2').is_file()
    assert not root.joinpath('etc', 'issue').exists()

    # <ln path="/etc/hosts">/etc/hosts3</ln>
    assert root.joinpath('etc', 'hosts3').is_symlink()
    assert str(root.joinpath('etc', 'hosts3').readlink()) == '/etc/hosts'

    # <addgroup gid="2001" system="false">testgroup</addgroup>
    # <adduser groups="nogroup,staff" shell="/bin/sh" uid="2000" gid="2001"
    #          home="/home/nottestuser" system="true" create_home="true" create_group="false">
    #   testuser
    # </adduser>

    assert '\ntestgroup:x:2001:\n' in root.joinpath('etc', 'group').read_text()

    assert '\ntestuser:x:2000:2001::/home/nottestuser:/bin/sh\n' in \
        root.joinpath('etc', 'passwd').read_text()

    # <file dst="/testfile" encoding="plain" owner="nobody" group="nogroup" mode="640">
    # 	Some cöntent wíth spe©ial characters
    # </file>
    assert root.joinpath('testfile').is_file()
    assert root.joinpath('testfile').read_text() == 'Some cöntent wíth spe©ial characters\n'

    # <command>cat /etc/hosts | cat -n > /etc/hosts4</command>
    assert root.joinpath('etc', 'hosts4').is_file()
    assert root.joinpath('etc', 'hosts4').read_text().startswith('     1\t127.0.0.1\tlocalhost\n')

    # <raw_cmd>cp /etc/hosts /etc/hosts5</raw_cmd>
    assert root.joinpath('etc', 'hosts5').is_file()
    assert root.joinpath('etc', 'hosts5').read_text().startswith('127.0.0.1\tlocalhost\n')

    # <command>ln /etc/hosts /etc/hosts6</command>
    assert root.joinpath('etc', 'hosts6').is_file()
    assert root.joinpath('etc', 'hosts').stat().st_ino == \
           root.joinpath('etc', 'hosts6').stat().st_ino

    # <command>cp /usr/sbin/policy-rc.d /usr/sbin/policy-rc.d.copy</command>
    copy = root.joinpath('usr', 'sbin', 'policy-rc.d.copy')
    assert copy.exists()
    assert copy.stat().st_mode & 0o777 == 0o755
    assert copy.read_text().strip() == textwrap.dedent("""
    #!/bin/sh
    exit 101
    """).strip()


def _test_archive(root):
    archive_file = root.joinpath('opt', 'archive-file')
    assert archive_file.is_file()

    archive_file_stat = archive_file.stat()
    assert archive_file_stat.st_uid == 0
    assert archive_file_stat.st_gid == 0


def _test_excursions(root):
    assert not root.joinpath('usr', 'sbin', 'policy-rc.d').exists()


def _test_grub(img, root, root_uuid):
    grub_cfg = root.joinpath('boot', 'grub', 'grub.cfg').read_text()
    assert f'root=UUID={root_uuid}' in grub_cfg
    assert b'GRUB' in img.read_at(512, 0)  # GRUB in MBR


def _test_rootfs(build_dir, root, image_name):
    assert root.joinpath('etc', 'hostname').read_text() == 'validation-image'
    assert root.joinpath('etc', 'mailname').read_text() == 'validation-image.elbe-ci'
    assert not root.joinpath('etc', 'resolv.conf').exists()
    assert root.joinpath('etc', 'machine-id').is_file()
    assert root.joinpath('etc', 'machine-id').stat().st_size == 0
    assert root.joinpath('etc', 'fstab').read_text().strip() == textwrap.dedent("""
    LABEL=rfs / ext4 defaults 0 0
    """).strip()
    assert root.joinpath('etc', 'os-release').read_text().strip() == textwrap.dedent("""
        PRETTY_NAME="Debian GNU/Linux 13 (trixie)"
        NAME="Debian GNU/Linux"
        VERSION_ID="13"
        VERSION="13 (trixie)"
        VERSION_CODENAME=trixie
        DEBIAN_VERSION_FULL=13.6
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"
    """).strip()
    assert root.joinpath('etc', 'apt', 'sources.list').read_text() in [
        # With and without source CDROM
        'deb-src [] http://deb.debian.org/debian trixie main\n'
        'deb [arch=amd64] http://deb.debian.org/debian trixie main',

        'deb [arch=amd64] http://deb.debian.org/debian trixie main',
    ]

    assert root.joinpath('etc', 'apt', 'trusted.gpg.d',
                         'elbe-xml-primary-key.gpg').read_bytes() == (
        b'\x983\x04g\xe1\xaa\xd5\x16\t+\x06\x01\x04\x01\xdaG\x0f\x01\x01\x07@FXu9\x7f8(\xf2Qy'
        b'\xd0\x0f\xfc\xce\xd6\xc4\xf1D\xb6\x15\xb2\xa4\n|\x9e\xf7\x9d\x16\x1a\x9a_J\xb4GDebia'
        b'n Stable Release Key (13/trixie) <debian-release@lists.debian.org>\x88\x96\x04\x13'
        b'\x16\x08\x00>\x16!\x04AX\x7f}\xb8\xc7t\xbc\xcf\x13\x14\x16v/g\xa0\xb2\xc3\x9d\xe4'
        b'\x05\x02g\xe1\xaa\xd5\x02\x1b\x03\x05\t\x0f\t\x9c\x00\x05\x0b\t\x08\x07\x02\x06\x15'
        b'\n\t\x08\x0b\x02\x04\x16\x02\x03\x01\x02\x1e\x01\x02\x17\x80\x00\n\t\x10v/g\xa0\xb2'
        b'\xc3\x9d\xe48\xd5\x00\xfe=K\xf7\xbdT\x0bg\xf6*v\rx\xf9\xcf\x1f;2\x95\x17\x9c\xb1\xc0'
        b'\x85?\xcb\xb0\x9e\xc9\xa1\xd9\xca\xa1\x01\x00\xf2k\xab\x12\xa7\\\x0bJO\xb0\x00:\x1ag'
        b'\xaf\xfe\\\xf41e2}\xeeX\xe83\x01\xea\xddz\x15\x0b\x88u\x04\x13\x16\n\x00\x1d\x16!'
        b'\x04\xcaa\x9de\xa7*{\xad\xfc\x96\xd2\x80\x19d\x18\xaa\xebt\xc8\xa1\x05\x02g\xe1\xabf'
        b"\x00\n\t\x10\x19d\x18\xaa\xebt\xc8\xa1\xc6p\x00\xffx\xbbX\xe5\x14\x0f'\x9a\xea\xd0"
        b'\x01Tg\xc5)\xf1\xe3\xeb \x1b}\xc2\x95\xaf\x91\x8b\xd1d\x8eB%\xcd\x01\x00\xb6a2\xa8M'
        b'\xf0\x98\xfdc\x99\x9c,\x04\x1d\xe6\xe93s+\xeb\xe0<\x95\xe9\xe3\xf2\x91s\x9b\xc9\x85'
        b'\x02\x89\x022\x04\x10\x01\n\x00\x1d\x16!\x04r\x03c\x0e,\x8errQhO\xeb\xc5\xce]\xc2'
        b'\xc5B\xcdY\x05\x02g\xe2\xfe}\x00\n\t\x10\xc5\xce]\xc2\xc5B\xcdY}\xd9\x0f\xf7G\xdb\\'
        b'\xec\x9dX\xd6\xf5\x89|.\xfe\xf6\x94\x8f\x14\xb1\xe4\xd94g\t#\x8f\xb3\xe2\xef\x83\xd9'
        b'!\xf7}sB\xee\x7f\xf8\xfbtA\xee$\xec\xe48\xab\xe4\xae\x94\xd8y\x03|2\xcfHMT\xccx\xd4'
        b'\x8e\xa1\t\xfc\xb6v,\xc6\x11\xea\x1dG\x08\xf7)\xbf\xbc\x9e\xa5\x88\x8b\x04\xd8\xafy'
        b'\x83\x01\xf6\x98\xe46\xe2\x8by\xf6\x932A~\xec\\N\x03\xb9\n\xa5\xacE\xb5%\x17\xa6*'
        b'\xce\xd6$\x1d\x84\xff\x82;\xb2j\x86\xdf\xef\xe6\xa9p(\x1c\xa9)\x14\x13&\xd6\xffm5\\u'
        b'N\x9d\xc4G\xa0\xb8T[38\xd9f_CK\x07\x92\x1f\xfb\x04\xa2\xb6\xcdK\x9e\xc5`\x04\xadC'
        b'\x1d\xdd\xcd\xc6\x1e\xfca\x02\xf4[lA\x08\xe7\xec\x1e\xbc\x9a*B\xd6\xea\xdauy\xf4\xe9'
        b'0w\xde\xe2P\xc4\x811o\x11f\x8e\xdc\xd9O\x11\xe0\xfa\xee\xec@*\x91\x06\xd5\xbf\xc2'
        b'\xcc\x1a\xb1\xf8\xe85E?\xb4\x89\x99\x16\xf6\x85\xd8\xa0\xa2H\xd1\\t\x1eV\x1e2\xb8n'
        b'\x13\xe44\x16\xac\xbf\x9d\x96\x1cZ\x1a\xb7\xcb\xa4\xee\x18/I\xfa\x1c\x81\xec=\xd9'
        b'\xeew\xb8\xf33Fh\x058\xc7\xbf\xba\xa6\xf9&\x94\x15\xa77\x03\xc7\xfc\x89Fm\xecZ\xfc_('
        b'\xfa\xb54\x01j\xef`%Qq\xb6\xdcJ\xc8$\xabP\xe5\xfdx\xdb\xbe\\}\x83\t\n\x9e\x16\x9cm'
        b'\x0eUP\xe06fJz\xa0\x19\xff\xa4P\xf5[\xccD\xd1~\x1d4w\x0c\xdc\x9ed\x08\x07\x99\xba'
        b'\xcc\xe3<\x86W\xbf\x0b\xaf\x026\x8e\x13\xb6q*\xf1\x83\x95\x04\xd6+\xcc\xd1\xe6\x1fm'
        b'\xbd\xcc\x0c}SC\xf8J\x8a\xd2\xa7\xc3\x183-&\xab\xbf[IR&=\xc6\xfcS\x0e\xdd\xa1\xa7'
        b'\xd0\xab:o\xb7&\x8d\xb0\x86\x8ei\xfbX\x11\x89Oc\xef\x1f\x808\x9a]j\xa2\x95\xb2\xec'
        b'\xe9\xed\xeb;u\xf8)e\xcb\xfd\x14\x7f\xbe@jbR\xac\x00\x18\x14R\t\x95\xcaV\x1f\xfe\xcd'
        b'Em\x8b\xfa}E\xa0\x83\xaf\xe7\x18\xf9\x87\xae\xf9\xb8x\x7fXYOL\xd4*\xad\x16\x8f\xa7Z'
    )

    sources_list_d = root.joinpath('etc', 'apt', 'sources.list.d')
    assert sources_list_d.is_dir()
    assert len(list(sources_list_d.iterdir())) == 0

    assert root.joinpath('etc', 'shadow').read_text().startswith('root:$6$')

    getty_service = root.joinpath('etc', 'systemd', 'system', 'getty.target.wants',
                                  'serial-getty@ttyS0.service')
    assert getty_service.is_symlink()
    assert str(getty_service.readlink()) == '/lib/systemd/system/serial-getty@.service'

    assert root.joinpath('usr', 'bin', 'unzip').is_file()
    assert root.joinpath('usr', 'lib', 'x86_64-linux-gnu', 'libgpio-3.0.1.so.3.0.0').is_file()

    assert not root.joinpath('var', 'cache', 'elbe').exists()

    _test_generated_elbe_files(build_dir, root, image_name)
    _test_finetuning(root, image_name)
    _test_archive(root)
    _test_excursions(root)


def _test_rfs_partition(build_dir, img, part, image_name):
    assert part.number == 1
    assert part.start == 1 * 1024 * 1024
    assert part.size == 999 * 1024 * 1024
    assert part.type == '83'

    blkid = part.blkid()
    assert blkid['USAGE'] == 'filesystem'
    assert blkid['TYPE'] == 'ext4'
    assert blkid['LABEL'] == 'rfs'

    with part.files() as root:
        statvfs = elbevalidate.statvfs(root)
        assert statvfs.f_bfree * statvfs.f_bsize > 100 * 1024 * 1024

        _test_rootfs(build_dir, root, image_name)
        _test_grub(img, root, blkid['UUID'])


def test_image(build_dir):
    image_config = get_image_configuration(build_dir)
    for image_name in image_config.disk_images:
        with elbevalidate.Image.from_file(build_dir / image_name) as img:
            assert img.size == 1000 * 1024 * 1024

            blkid = img.blkid()
            assert blkid['PTTYPE'] == 'dos'

            partitions = img.partitions
            assert len(partitions) == 1

            _test_rfs_partition(build_dir, img, partitions[0], image_config.name)

    for image_name in image_config.tar_images:
        with elbevalidate.Tar.from_file(build_dir / image_name) as tar:
            with tar.files() as root:
                _test_rootfs(build_dir, root, image_config.name)


def _test_sdk_host_sysroot(sysroot):
    assert sysroot.joinpath('usr', 'bin', 'gcc').is_file()
    assert sysroot.joinpath('usr', 'bin', 'ld').is_file()


def _test_sdk_target_sysroot(sysroot):
    assert sysroot.joinpath('usr', 'include', 'syscall.h').is_file()
    assert sysroot.joinpath('usr', 'include', 'gpio.h').is_file()
    assert sysroot.joinpath('usr', 'lib', 'x86_64-linux-gnu', 'pkgconfig', 'libgpio.pc').is_file()
    assert sysroot.joinpath('usr', 'lib', 'x86_64-linux-gnu', 'libgpio.so').is_symlink()
    assert sysroot.joinpath('usr', 'share', 'doc', 'libc6-dev', 'copyright').is_file()


def test_sdk(build_dir):
    sdk = build_dir / 'setup-elbe-sdk-x86_64-linux-gnu-simple-validation-image-1.0.sh'

    if not sdk.is_file():
        raise unittest.SkipTest('no sdk has been built')

    # The script is self extracting; it needs to be executable
    sdk.chmod(0o755)

    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)

        subprocess.check_call([sdk, '-y', '-d', tmp])

        _test_sdk_host_sysroot(tmp / 'sysroots' / 'host')
        _test_sdk_target_sysroot(tmp / 'sysroots' / 'target')


if __name__ == '__main__':
    elbevalidate.pytest.run_with_pytest(__file__, sys.argv[1])
