# ELBE - Debian Based Embedded Rootfilesystem Builder
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2014-2015 Silvio Fricke <silvio.fricke@gmail.com>
# SPDX-FileCopyrightText: 2018 Linutronix GmbH

# This Dockerfile generate a image for the elbe buildsystem
FROM debian:trixie-slim

USER root
ENV DEBIAN_FRONTEND noninteractive

# update, upgrade and install elbe runtime-dependencies
RUN apt-get update -y
RUN apt-get install -y --no-install-recommends \
                    -o Dpkg::Options::="--force-confnew" \
        ca-certificates \
        sudo \
        vim-nox \
        elbe-archive-keyring \
        gnupg \
        python3-setuptools \
        python3-yaml \
        python3-jsonschema \
        locales \
        gcc \
        g++ \
        diffstat \
        texinfo \
        gawk \
        chrpath \
        python3-mako \
        fuseiso9660 \
        aptly \
        debian-archive-keyring \
        qemu-system-x86

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# install current elbe
RUN echo 'deb [signed-by=/usr/share/keyrings/elbe-archive-keyring.gpg] http://debian.linutronix.de/elbe bullseye main' >> /etc/apt/sources.list
RUN apt-get update -y
RUN apt-get install -y --no-install-recommends \
        elbe \
        elbe-doc
RUN apt-get clean -y
RUN rm -rf /var/lib/apt/lists/*

# create elbe user
RUN groupadd -g @KVMGID@ -o -r kvm-elbe
RUN useradd -d /home/elbe -l -U -G kvm-elbe,libvirt -m -s /bin/bash -u @USERID@ elbe
RUN echo "root:elbe" | chpasswd
RUN echo "elbe:elbe" | chpasswd

VOLUME [ "/sys/fs/cgroup" ]
VOLUME [ "/elbe" ]
VOLUME [ "/var/cache/elbe" ]

# sudo for elbe
RUN echo "%elbe  ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/elbegrp
RUN chmod 0440 /etc/sudoers.d/elbegrp


CMD [ "/bin/bash" ]
