# ELBE - Debian Based Embedded Rootfilesystem Builder
# Copyright (c) 2017 Torben Hohn <torben.hohn@linutronix.de>
# Copyright (c) 2017 Manuel Traut <manut@linutronix.de>
# Copyright (c) 2019 Olivier Dion <dion@linutronix.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

import os
import stat

from shutil import copyfile

from elbepack.debianize.panels.base import Panel
from elbepack.debianize.widgets.edit import Edit

from elbepack.directories import mako_template_dir
from elbepack.templates import template
from elbepack.shellhelper import system


class BareBox(Panel):

    match_files = ['Kbuild', 'Kconfig', 'README', 'Documentation/barebox.svg']

    def __init__(self):

        imgname = Edit("Image name", "barebox-phytec-phycore-imx6dl-som-nand-256mb.img")
        defconfig = Edit("Def config", "imx_v7_defconfig")
        cross = Edit("CROSS_COMPILE", "arm-linux-gnueabihf-")
        k_version = Edit("BareBox Version", "2016.10")

        grid_elements = [
            {"imgname":imgname, "defconfig":defconfig},
            {"cross_compile":cross, "k_version":k_version}
        ]

        super(BareBox, self).__init__(grid_elements)

    def debianize(self):

        self.tmpl_dir = os.path.join(mako_template_dir, 'debianize/barebox')
        pkg_name = self.deb['p_name'] + '-' + self.deb['k_version']

        for tmpl in ['control', 'rules']:
            with open(os.path.join('debian/', tmpl), 'w') as f:
                mako = os.path.join(self.tmpl_dir, tmpl + '.mako')
                f.write(template(mako, self.deb))

        st = os.stat(os.path.join('debian', 'rules'))
        os.chmod(os.path.join('debian', 'rules'), st.st_mode | stat.S_IEXEC)

        cmd = 'dch --package barebox-' + pkg_name + \
            ' -v ' + self.deb['p_version'] + \
            ' --create -M -D ' + self.deb['release'] + \
            ' "generated by elbe debianize"'
        system(cmd)

        copyfile(os.path.join(self.tmpl_dir, 'barebox-image.install'),
                 'debian/barebox-image-' + pkg_name + '.install')
        copyfile(os.path.join(self.tmpl_dir, 'barebox-tools.install'),
                 'debian/barebox-tools-' + pkg_name + '.install')

        self.hint = "use 'dpkg-buildpackage -a%s' to build the package" % (
                self.deb['p_arch'])
