# ELBE - Debian Based Embedded Rootfilesystem Builder
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2014-2015 Silvio Fricke <silvio.fricke@gmail.com>
# SPDX-FileCopyrightText: 2018 Linutronix GmbH

# This Containerfile generates an image for the elbe buildsystem
FROM debian:trixie-slim

USER root
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        elbe-archive-keyring \
        tini

RUN echo 'deb [signed-by=/usr/share/keyrings/elbe-archive-keyring.gpg] http://debian.linutronix.de/elbe trixie main' \
        > /etc/apt/sources.list.d/elbe.list && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
        python3-elbe-daemon \
        python3-elbe-soap \
        python3-elbe-control \
        locales && \
    apt-get clean -y

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

VOLUME [ "/build" ]

USER root
WORKDIR /build

# Use tini for reaping child processes.
ENTRYPOINT ["tini", "--", "/entrypoint.sh"]
